baseURL = "https://til.faizmokhtar.com/"
title = "til."
languageCode = "en-us"
theme = "hugo-tailwind-journal"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsOptions = "linenos=1"
pygmentsStyle = "dracula"

[taxonomies]
    tag = "tags"

[params]
    author = "Faiz Mokhtar"
    description = "Today I learned!"
    tagline = "Today I learned!"

[languages]
    [languages.en]
        contentDir = "content"
        languageCode = "en-us"
        languageName = "🇺🇸 English"
        weight = 1