baseURL = "https://til.faizmokhtar.com/"
title = "til."
languageCode = "en-us"
theme = "hugo-tailwind-journal"
pygmentsCodeFences = true
pygmentsUseClasses = true

[taxonomies]
    tag = "tags"

[permalinks]
    posts = "/posts/:year/:month/:title/"

[params]
    author = "John Doe"
    description = "Today I learned!"
    tagline = "Today I learned!"

[languages]
    [languages.en]
        contentDir = "content/english"
        languageCode = "en-us"
        languageName = "🇺🇸 English"
        weight = 1