backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "post"
    label: "Post"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish date", name: "date", widget: "datetime"}
      - {label: "Categories", name: "categories", required: false, widget: "list"}
      - {label: "Tags", name: "tags", required: false, widget: "list"}
      - {label: "Enable comments", name: "comments", default: true, widget: "boolean"}
      - {label: "Body", name: "body", widget: "markdown"}